postprocessor:
  name: kan
  APS_mode: False
  postprocessor_args:
    grid_size: 100
    num_partitions: 10
  postprocessor_sweep:
    grid_size: [5, 10, 50, 100, 200]
    num_partitions: [1, 5, 10, 20, 30] 